# Generated by Django 3.0.5 on 2020-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_algo', models.CharField(choices=[('BM25', 'OKAPI BM-25'), ('DFR', 'Divergence from Randomness (DFR)'), ('DFI', 'Divergence from Independence (DFI)'), ('LMD', 'LM Dirichlet')], max_length=50)),
            ],
        ),
    ]
