# Generated by Django 3.0.5 on 2020-08-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='current_algo',
            new_name='algorithm',
        ),
    ]
