# Generated by Django 3.0.5 on 2020-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200908_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='after_effect',
            field=models.CharField(choices=[('b', 'Bernoulli processes'), ('l', "Laplace's law of succession")], default='b', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='b',
            field=models.CharField(default='0.75', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='basic_model',
            field=models.CharField(choices=[('g', 'Geometric approximation of Bose-Einstein'), ('if', 'Inverse Term Frequency'), ('in', 'Inverse Document Frequency'), ('ine', 'Inverse Expected Document Frequency')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='discount_overlaps',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='True', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='distribution',
            field=models.CharField(choices=[('ll', 'Log-logistic'), ('spl', 'Smoothed power-law')], default='ll', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='independence_measure',
            field=models.CharField(choices=[('standardized', 'Standardized'), ('saturated', 'Saturated'), ('chisquared', 'Normalized chi-squared')], default='standardized', max_length=15),
        ),
        migrations.AddField(
            model_name='config',
            name='k1',
            field=models.CharField(default='1.2', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='lambda_ib',
            field=models.CharField(choices=[('df', 'Document frequency'), ('ttf', 'Total term frequency')], default='df', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='lambda_jelinek',
            field=models.CharField(default='.1', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='mu',
            field=models.CharField(default='2000', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='normalization_dfr',
            field=models.CharField(choices=[('no', 'no'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('z', 'z')], default='h1', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='normalization_ib',
            field=models.CharField(choices=[('no', 'no'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('z', 'z')], default='h1', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='normalization_parameter_dfr',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='config',
            name='normalization_parameter_ib',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
