# Generated by Django 3.0.5 on 2020-10-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_searchconfig_searchebleindicesconfigs_searchfieldsweightsconfigs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchFieldsWeightsConfigs',
            new_name='WeigtedSeachFieldsConfigs',
        ),
    ]
