# Generated by Django 3.0.5 on 2020-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201008_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightedSearchFieldsConfigs',
            fields=[
                ('field', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=1)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeigtedSeachFieldsConfigs',
        ),
        migrations.RenameField(
            model_name='searchebleindicesconfigs',
            old_name='searchble',
            new_name='searchable',
        ),
        migrations.AlterField(
            model_name='searchconfig',
            name='results_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
