# Generated by Django 3.0.5 on 2020-10-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201008_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchebleIndicesConfigs',
            new_name='SearchableIndicesConfigs',
        ),
    ]
