# Generated by Django 3.0.5 on 2020-10-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20201009_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchConfig',
            new_name='SearchConfigs',
        ),
    ]
