# Generated by Django 3.0.5 on 2020-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201009_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchableindicesconfigs',
            name='index_model',
            field=models.CharField(default='Diario', max_length=50),
            preserve_default=False,
        ),
    ]
