# Generated by Django 3.0.5 on 2020-10-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20201021_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchconfigs',
            name='id',
        ),
        migrations.AlterField(
            model_name='searchableindicesconfigs',
            name='index_model',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Processo', 'Processo'), ('Licitacao', 'Licitacao')], max_length=50),
        ),
        migrations.AlterField(
            model_name='searchconfigs',
            name='results_per_page',
            field=models.IntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
