# Generated by Django 3.0.5 on 2020-10-30 16:25

from django.db import migrations

def insert_configs_data(apps, schema_editor):

        SearchableIndicesConfigs = apps.get_model('services', 'SearchableIndicesConfigs')
        for row in SearchableIndicesConfigs.objects.all():
            row.delete()
        SearchableIndicesConfigs(index='diarios',           index_model='Diario',         searchable=True,  group='regular').save()
        SearchableIndicesConfigs(index='processos',         index_model='Processo',       searchable=True,  group='regular').save()
        SearchableIndicesConfigs(index='diarios_entidades', index_model='DiarioEntidade', searchable=False, group='regular').save()
        SearchableIndicesConfigs(index='diarios-replica',   index_model='Diario',         searchable=True,  group='replica').save()
        SearchableIndicesConfigs(index='processos-replica', index_model='Processo',       searchable=True,  group='replica').save()
        SearchableIndicesConfigs(index='licitacoes',        index_model='Licitacao',      searchable=True,  group='regular').save()

        WeightedSearchFieldsConfigs = apps.get_model('services', 'WeightedSearchFieldsConfigs')
        for row in WeightedSearchFieldsConfigs.objects.all():
            row.delete()
        WeightedSearchFieldsConfigs(field='titulo',   field_name='Titulo',   weight=1, searchable=True ).save()
        WeightedSearchFieldsConfigs(field='conteudo', field_name='Conteudo', weight=1, searchable=False).save()

class Migration(migrations.Migration):
    
    dependencies = [
        ('services', '0014_auto_20201030_0833'),
    ]

    operations = [
        migrations.RunPython(insert_configs_data),
    ]
