# Generated by Django 3.0.5 on 2020-10-30 19:35

from django.db import migrations

def insert_configs_data(apps, schema_editor):

        SearchableIndicesConfigs = apps.get_model('services', 'SearchableIndicesConfigs')
        SearchableIndicesConfigs(
            index='licitacoes-replica', 
            index_model='Licitacao', 
            searchable=True, 
            group='replica' ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20201030_1325'),
    ]

    operations = [
        migrations.RunPython(insert_configs_data),
    ]
