# Generated by Django 3.0.5 on 2020-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20201030_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconfigs',
            name='use_entities_in_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='searchableindicesconfigs',
            name='index_model',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Processo', 'Processo'), ('Licitacao', 'Licitacao'), ('DiarioEntidade', 'DiarioEntidade')], max_length=50),
        ),
    ]
