# Generated by Django 3.0.5 on 2020-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20201120_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='compare',
        ),
    ]
