# Generated by Django 3.0.5 on 2020-11-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_config_compare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightedsearchfieldsconfigs',
            name='field_name',
        ),
    ]
