# Generated by Django 3.0.5 on 2020-12-03 19:39

from django.db import migrations

def insert_configs_data(apps, schema_editor):
        SearchableIndicesConfigs = apps.get_model('services', 'SearchableIndicesConfigs')
        try:
            SearchableIndicesConfigs.objects.get(index='diarios_entidades').delete()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_weightedsearchfieldsconfigs_field_name'),
    ]

    operations = [
        migrations.RunPython(insert_configs_data),
    ]
