# Generated by Django 3.0.5 on 2021-08-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20201203_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchableindicesconfigs',
            name='index_model',
            field=models.CharField(choices=[('Diario', 'Diario'), ('DiarioSegmentado', 'DiarioSegmentado'), ('Processo', 'Processo'), ('Licitacao', 'Licitacao')], max_length=50),
        ),
    ]
