# Generated by Django 3.0.5 on 2021-08-05 21:16

from django.db import migrations


def insert_configs_data(apps, schema_editor):

    SearchableIndicesConfigs = apps.get_model('services', 'SearchableIndicesConfigs')
    SearchableIndicesConfigs(index='diarios_segmentado', index_model='DiarioSegmentado', searchable=True,  group='regular').save()



class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20210805_1811'),
    ]

    operations = [
        migrations.RunPython(insert_configs_data),
    ]
